# Datasource
spring.datasource.url=${DATASOURCE_HML_URL}
spring.datasource.username=${DATASOURCE_HML_USERNAME}
spring.datasource.password=${DATASOURCE_HML_PASSWORD}

# JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate