application.propertiesgit pull origin masterspring.application.name=projetoAula
# Datasource
spring.datasource.url=jdbc:h2:mem:usuarios
spring.datasource.username=sa
spring.datasource.password=

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console # Permite acessar o banco H2 em localhost:<PORTA>/h2-console

# JPA
spring.jpa.show-sql=true # Mostra SQL no console
spring.jpa.hibernate.ddl-auto=update