application.propertiesgit pull origin masterspring.application.name=projetoAula
# Datasource
spring.datasource.url=${DATASOURCE_PRD_URL}
spring.datasource.username=${DATASOURCE_PRD_USERNAME}
spring.datasource.password=${DATASOURCE_PRD_PASSWORD}

# JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate